"""Initial schema

Revision ID: 88e8ec081a06
Revises: 
Create Date: 2026-04-24 00:29:11.484170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88e8ec081a06'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('dni', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('telegram_chat_id', sa.String(), nullable=True),
    sa.Column('license_type', sa.String(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('assigned_truck_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_truck_id'], ['trucks.id'], name='fk_user_assigned_truck', use_alter=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_assigned_truck_id'), 'users', ['assigned_truck_id'], unique=False)
    op.create_index(op.f('ix_users_created_by_id'), 'users', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_users_dni'), 'users', ['dni'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_telegram_chat_id'), 'users', ['telegram_chat_id'], unique=False)
    op.create_index('ix_users_truck_role', 'users', ['assigned_truck_id', 'role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('salaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('date_paid', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salaries_date_paid'), 'salaries', ['date_paid'], unique=False)
    op.create_index(op.f('ix_salaries_id'), 'salaries', ['id'], unique=False)
    op.create_index('ix_salaries_user_date', 'salaries', ['user_id', 'date_paid'], unique=False)
    op.create_index(op.f('ix_salaries_user_id'), 'salaries', ['user_id'], unique=False)
    op.create_table('trucks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('capacity_tons', sa.Float(), nullable=True),
    sa.Column('current_balance', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('current_travel_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trucks_id'), 'trucks', ['id'], unique=False)
    op.create_index(op.f('ix_trucks_owner_id'), 'trucks', ['owner_id'], unique=False)
    op.create_index(op.f('ix_trucks_plate'), 'trucks', ['plate'], unique=True)
    op.create_index(op.f('ix_trucks_status'), 'trucks', ['status'], unique=False)
    op.create_table('owner_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('date_recorded', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('truck_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owner_notes_category'), 'owner_notes', ['category'], unique=False)
    op.create_index(op.f('ix_owner_notes_date_recorded'), 'owner_notes', ['date_recorded'], unique=False)
    op.create_index(op.f('ix_owner_notes_id'), 'owner_notes', ['id'], unique=False)
    op.create_index('ix_owner_notes_owner_date', 'owner_notes', ['owner_id', 'date_recorded'], unique=False)
    op.create_index(op.f('ix_owner_notes_owner_id'), 'owner_notes', ['owner_id'], unique=False)
    op.create_index(op.f('ix_owner_notes_truck_id'), 'owner_notes', ['truck_id'], unique=False)
    op.create_table('travels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('loaded_at', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('truck_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('official_id', sa.Integer(), nullable=False),
    sa.Column('extra_official_id', sa.Integer(), nullable=True),
    sa.Column('material_type', sa.String(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('start_odometer', sa.Float(), nullable=True),
    sa.Column('start_odometer_photo_url', sa.String(), nullable=True),
    sa.Column('end_odometer', sa.Float(), nullable=True),
    sa.Column('end_odometer_photo_url', sa.String(), nullable=True),
    sa.Column('billing_status', sa.String(), nullable=True),
    sa.Column('amount_paid', sa.Float(), nullable=True),
    sa.Column('invoice_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['extra_official_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['official_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_travels_billing_status'), 'travels', ['billing_status'], unique=False)
    op.create_index(op.f('ix_travels_driver_id'), 'travels', ['driver_id'], unique=False)
    op.create_index(op.f('ix_travels_id'), 'travels', ['id'], unique=False)
    op.create_index(op.f('ix_travels_loaded_at'), 'travels', ['loaded_at'], unique=False)
    op.create_index(op.f('ix_travels_material_type'), 'travels', ['material_type'], unique=False)
    op.create_index(op.f('ix_travels_status'), 'travels', ['status'], unique=False)
    op.create_index(op.f('ix_travels_truck_id'), 'travels', ['truck_id'], unique=False)
    op.create_index('ix_travels_truck_status_end', 'travels', ['truck_id', 'status', 'end_time'], unique=False)
    op.create_table('truck_funds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('truck_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_truck_funds_created_at'), 'truck_funds', ['created_at'], unique=False)
    op.create_index(op.f('ix_truck_funds_id'), 'truck_funds', ['id'], unique=False)
    op.create_index('ix_truck_funds_truck_date', 'truck_funds', ['truck_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_truck_funds_truck_id'), 'truck_funds', ['truck_id'], unique=False)
    op.create_table('advances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('travel_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('date_given', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['travel_id'], ['travels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advances_date_given'), 'advances', ['date_given'], unique=False)
    op.create_index(op.f('ix_advances_id'), 'advances', ['id'], unique=False)
    op.create_index(op.f('ix_advances_travel_id'), 'advances', ['travel_id'], unique=False)
    op.create_index('ix_advances_user_date', 'advances', ['user_id', 'date_given'], unique=False)
    op.create_index(op.f('ix_advances_user_id'), 'advances', ['user_id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('truck_id', sa.Integer(), nullable=True),
    sa.Column('travel_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('gallons', sa.Float(), nullable=True),
    sa.Column('odometer_reading', sa.Float(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['travel_id'], ['travels.id'], ),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_category'), 'expenses', ['category'], unique=False)
    op.create_index(op.f('ix_expenses_created_at'), 'expenses', ['created_at'], unique=False)
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.create_index('ix_expenses_travel_date', 'expenses', ['travel_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_expenses_travel_id'), 'expenses', ['travel_id'], unique=False)
    op.create_index('ix_expenses_truck_date', 'expenses', ['truck_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_expenses_truck_id'), 'expenses', ['truck_id'], unique=False)
    op.create_index(op.f('ix_expenses_user_id'), 'expenses', ['user_id'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('truck_id', sa.Integer(), nullable=True),
    sa.Column('travel_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('device_time', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['travel_id'], ['travels.id'], ),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_device_time'), 'locations', ['device_time'], unique=False)
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_index(op.f('ix_locations_travel_id'), 'locations', ['travel_id'], unique=False)
    op.create_index('ix_locations_travel_time', 'locations', ['travel_id', 'device_time'], unique=False)
    op.create_index(op.f('ix_locations_truck_id'), 'locations', ['truck_id'], unique=False)
    op.create_index('ix_locations_truck_time', 'locations', ['truck_id', 'device_time'], unique=False)
    op.create_table('travel_destinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('travel_id', sa.Integer(), nullable=True),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('packing_list_url', sa.String(), nullable=True),
    sa.Column('stowage_photo_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['travel_id'], ['travels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_travel_destinations_client_name'), 'travel_destinations', ['client_name'], unique=False)
    op.create_index(op.f('ix_travel_destinations_id'), 'travel_destinations', ['id'], unique=False)
    op.create_index(op.f('ix_travel_destinations_status'), 'travel_destinations', ['status'], unique=False)
    op.create_index(op.f('ix_travel_destinations_travel_id'), 'travel_destinations', ['travel_id'], unique=False)
    op.create_table('travel_guides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=False),
    sa.Column('guide_type', sa.Enum('carga', 'entrega', name='guidetype'), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['travel_destinations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_travel_guides_destination_id'), 'travel_guides', ['destination_id'], unique=False)
    op.create_index(op.f('ix_travel_guides_guide_type'), 'travel_guides', ['guide_type'], unique=False)
    op.create_index(op.f('ix_travel_guides_id'), 'travel_guides', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_travel_guides_id'), table_name='travel_guides')
    op.drop_index(op.f('ix_travel_guides_guide_type'), table_name='travel_guides')
    op.drop_index(op.f('ix_travel_guides_destination_id'), table_name='travel_guides')
    op.drop_table('travel_guides')
    op.drop_index(op.f('ix_travel_destinations_travel_id'), table_name='travel_destinations')
    op.drop_index(op.f('ix_travel_destinations_status'), table_name='travel_destinations')
    op.drop_index(op.f('ix_travel_destinations_id'), table_name='travel_destinations')
    op.drop_index(op.f('ix_travel_destinations_client_name'), table_name='travel_destinations')
    op.drop_table('travel_destinations')
    op.drop_index('ix_locations_truck_time', table_name='locations')
    op.drop_index(op.f('ix_locations_truck_id'), table_name='locations')
    op.drop_index('ix_locations_travel_time', table_name='locations')
    op.drop_index(op.f('ix_locations_travel_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_device_time'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_expenses_user_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_truck_id'), table_name='expenses')
    op.drop_index('ix_expenses_truck_date', table_name='expenses')
    op.drop_index(op.f('ix_expenses_travel_id'), table_name='expenses')
    op.drop_index('ix_expenses_travel_date', table_name='expenses')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_created_at'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_category'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_advances_user_id'), table_name='advances')
    op.drop_index('ix_advances_user_date', table_name='advances')
    op.drop_index(op.f('ix_advances_travel_id'), table_name='advances')
    op.drop_index(op.f('ix_advances_id'), table_name='advances')
    op.drop_index(op.f('ix_advances_date_given'), table_name='advances')
    op.drop_table('advances')
    op.drop_index(op.f('ix_truck_funds_truck_id'), table_name='truck_funds')
    op.drop_index('ix_truck_funds_truck_date', table_name='truck_funds')
    op.drop_index(op.f('ix_truck_funds_id'), table_name='truck_funds')
    op.drop_index(op.f('ix_truck_funds_created_at'), table_name='truck_funds')
    op.drop_table('truck_funds')
    op.drop_index('ix_travels_truck_status_end', table_name='travels')
    op.drop_index(op.f('ix_travels_truck_id'), table_name='travels')
    op.drop_index(op.f('ix_travels_status'), table_name='travels')
    op.drop_index(op.f('ix_travels_material_type'), table_name='travels')
    op.drop_index(op.f('ix_travels_loaded_at'), table_name='travels')
    op.drop_index(op.f('ix_travels_id'), table_name='travels')
    op.drop_index(op.f('ix_travels_driver_id'), table_name='travels')
    op.drop_index(op.f('ix_travels_billing_status'), table_name='travels')
    op.drop_table('travels')
    op.drop_index(op.f('ix_owner_notes_truck_id'), table_name='owner_notes')
    op.drop_index(op.f('ix_owner_notes_owner_id'), table_name='owner_notes')
    op.drop_index('ix_owner_notes_owner_date', table_name='owner_notes')
    op.drop_index(op.f('ix_owner_notes_id'), table_name='owner_notes')
    op.drop_index(op.f('ix_owner_notes_date_recorded'), table_name='owner_notes')
    op.drop_index(op.f('ix_owner_notes_category'), table_name='owner_notes')
    op.drop_table('owner_notes')
    op.drop_index(op.f('ix_trucks_status'), table_name='trucks')
    op.drop_index(op.f('ix_trucks_plate'), table_name='trucks')
    op.drop_index(op.f('ix_trucks_owner_id'), table_name='trucks')
    op.drop_index(op.f('ix_trucks_id'), table_name='trucks')
    op.drop_table('trucks')
    op.drop_index(op.f('ix_salaries_user_id'), table_name='salaries')
    op.drop_index('ix_salaries_user_date', table_name='salaries')
    op.drop_index(op.f('ix_salaries_id'), table_name='salaries')
    op.drop_index(op.f('ix_salaries_date_paid'), table_name='salaries')
    op.drop_table('salaries')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index('ix_users_truck_role', table_name='users')
    op.drop_index(op.f('ix_users_telegram_chat_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_dni'), table_name='users')
    op.drop_index(op.f('ix_users_created_by_id'), table_name='users')
    op.drop_index(op.f('ix_users_assigned_truck_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
