"""update db schema

Revision ID: 93550173e06b
Revises: 88e8ec081a06
Create Date: 2026-04-25 23:29:25.405830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93550173e06b'
down_revision: Union[str, Sequence[str], None] = '88e8ec081a06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_user_assigned_truck', 'users', 'trucks', ['assigned_truck_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_assigned_truck', 'users', type_='foreignkey')
    # ### end Alembic commands ###
